from datetime import datetime, timezone
from typing import Any, Dict, List, Literal, Optional
from uuid import uuid4
from pydantic import BaseModel, Field


class Message(BaseModel):
    """Represents a chat message within the conversation history."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    role: Literal["user", "assistant", "system"]
    content: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class Action(BaseModel):
    """Represents an executable action generated by the agent's Action Engine."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    action_type: str  # e.g., "web_search", "open_app", "command_execution", "tts"
    parameters: Dict[str, Any] = Field(default_factory=dict)


class ActionResult(BaseModel):
    """Represents the outcome of executing a specific Action."""

    action_id: str
    status: Literal["success", "failure"]
    output: Optional[str] = None
    error_message: Optional[str] = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class AgentResponse(BaseModel):
    """Represents the complete response from the agent, combining text and potential actions."""

    response_id: str = Field(default_factory=lambda: str(uuid4()))
    message: Message
    actions: List[Action] = Field(default_factory=list)
    action_results: List[ActionResult] = Field(default_factory=list)
    metadata: Dict[str, Any] = Field(default_factory=dict)


class InstalledApp(BaseModel):
    """Represents a GUI application installed on the system, parsed from desktop entries."""

    name: str
    exec_command: str
    generic_name: Optional[str] = None
    categories: List[str] = Field(default_factory=list)
    keywords: List[str] = Field(default_factory=list)
