from typing import List, Optional
from src.domain.entities import AgentResponse, Message
from src.domain.interfaces.llm import AbstractLLMService
from src.utils.logging import get_logger

logger = get_logger("chat_use_case")


class ChatUseCase:
    """Application use case that orchestrates the message exchange process.

    Coordinates the formatting of conversation history and invocation of the LLM.
    """

    def __init__(self, llm_service: AbstractLLMService):
        """Initializes the use case with an LLM service adapter.

        Uses Dependency Inversion to remain decoupled from vendor SDK details.
        """
        self.llm_service = llm_service

    def execute(
        self,
        history: List[Message],
        user_input: str,
        system_instruction: Optional[str] = None,
    ) -> AgentResponse:
        """Appends the new user query, triggers LLM reasoning, and returns the response.

        Args:
            history: List of past Messages in the current session.
            user_input: The new message query text from the user.
            system_instruction: Optional instruction defining the model persona.

        Returns:
            The AgentResponse generated by the LLM service.
        """
        logger.info(f"Processing chat use case for user input: '{user_input[:40]}...'")

        # 1. Instantiate the user message entity
        user_msg = Message(role="user", content=user_input)

        # 2. Append the new message to the active history context
        context_messages = history + [user_msg]

        # 3. Request generative completion from the injected LLM service
        agent_response = self.llm_service.generate_response(
            messages=context_messages,
            system_instruction=system_instruction,
        )

        return agent_response
